-- Seed data for people table
INSERT INTO people (id, name, description, birth, death, birth_place, occupation, background, documents, events, connections) VALUES

('lee-harvey-oswald',
 'Lee Harvey Oswald',
 'Figure identified as the primary suspect in the assassination of President John F. Kennedy.',
 '1939-10-18',
 '1963-11-24',
 'New Orleans, Louisiana',
 'Former U.S. Marine, Factory Worker',
 'Lee Harvey Oswald was a former U.S. Marine who defected to the Soviet Union in 1959, returning to the United States in 1962 with his Russian wife Marina. He worked at the Texas School Book Depository in Dallas at the time of the assassination. He was arrested for the murder of Dallas police officer J.D. Tippit and later charged with assassinating President Kennedy. He was shot and killed by Jack Ruby two days after the assassination while being transferred between jails.',
 '[{"title": "Warren Commission Report", "href": "#"}, {"title": "HSCA Report Volume XI", "href": "#"}, {"title": "Military Service Record", "href": "#"}]'::jsonb,
 '[{"title": "JFK Assassination", "href": "#"}, {"title": "Time in Soviet Union", "href": "#"}, {"title": "Shooting of J.D. Tippit", "href": "#"}]'::jsonb,
 '[{"name": "Marina Oswald Porter", "href": "/people/marina-oswald-porter"}, {"name": "Jack Ruby", "href": "/people/jack-ruby"}, {"name": "George de Mohrenschildt", "href": "/people/george-de-mohrenschildt"}]'::jsonb),

('jack-ruby',
 'Jack Ruby',
 'Dallas nightclub owner who shot and killed Lee Harvey Oswald on November 24, 1963.',
 '1911-03-25',
 '1967-01-03',
 'Chicago, Illinois',
 'Nightclub Owner',
 'Jack Ruby, born Jacob Leon Rubenstein, operated the Carousel Club, a Dallas nightclub. On November 24, 1963, he shot and killed Lee Harvey Oswald in the basement of Dallas Police Headquarters during a jail transfer, an event broadcast live on national television. Ruby was convicted of murder and sentenced to death, but the conviction was overturned on appeal. He died of lung cancer while awaiting a new trial.',
 '[{"title": "Warren Commission Testimony", "href": "#"}, {"title": "FBI Background Report", "href": "#"}]'::jsonb,
 '[{"title": "Shooting of Lee Harvey Oswald", "href": "#"}, {"title": "Ruby Trial", "href": "#"}]'::jsonb,
 '[{"name": "Lee Harvey Oswald", "href": "/people/lee-harvey-oswald"}]'::jsonb),

('john-f-kennedy',
 'John F. Kennedy',
 '35th President of the United States, assassinated in Dallas, Texas on November 22, 1963.',
 '1917-05-29',
 '1963-11-22',
 'Brookline, Massachusetts',
 '35th President of the United States',
 'John Fitzgerald Kennedy served as the 35th President of the United States from January 1961 until his assassination. A decorated World War II naval officer and U.S. Senator from Massachusetts, Kennedy was the youngest person elected to the presidency. He was assassinated while riding in a motorcade through Dealey Plaza in Dallas, Texas. His death prompted the largest criminal investigation in U.S. history and continues to be the subject of significant debate and research.',
 '[{"title": "Autopsy Report", "href": "#"}, {"title": "Warren Commission Report", "href": "#"}]'::jsonb,
 '[{"title": "JFK Assassination", "href": "#"}, {"title": "Motorcade Through Dallas", "href": "#"}]'::jsonb,
 '[{"name": "Jacqueline Kennedy", "href": "/people/jacqueline-kennedy"}, {"name": "Lyndon B. Johnson", "href": "/people/lyndon-b-johnson"}]'::jsonb),

('jacqueline-kennedy',
 'Jacqueline Kennedy',
 'First Lady of the United States and wife of President John F. Kennedy.',
 '1929-07-28',
 '1994-05-19',
 'Southampton, New York',
 'First Lady of the United States',
 'Jacqueline Lee Kennedy Onassis served as First Lady during her husband''s presidency. She was seated next to him in the presidential limousine during the assassination and cradled him after he was shot. Her composure and dignity during the funeral proceedings earned widespread admiration. She later married Greek shipping magnate Aristotle Onassis and worked as a book editor in New York City.',
 '[{"title": "Warren Commission Testimony", "href": "#"}]'::jsonb,
 '[{"title": "JFK Assassination", "href": "#"}]'::jsonb,
 '[{"name": "John F. Kennedy", "href": "/people/john-f-kennedy"}]'::jsonb),

('marina-oswald-porter',
 'Marina Oswald Porter',
 'Soviet-born wife of Lee Harvey Oswald.',
 '1941-07-17',
 NULL,
 'Severodvinsk, Soviet Union',
 'Pharmacist',
 'Marina Nikolayevna Oswald Porter met Lee Harvey Oswald at a dance in Minsk in March 1961. They married six weeks later and moved to the United States in June 1962. She provided crucial testimony to the Warren Commission, including information about Oswald''s attempted shooting of General Edwin Walker. She has since remarried and continues to live in the Dallas area.',
 '[{"title": "Warren Commission Testimony", "href": "#"}, {"title": "HSCA Testimony", "href": "#"}]'::jsonb,
 '[{"title": "Life in Soviet Union", "href": "#"}]'::jsonb,
 '[{"name": "Lee Harvey Oswald", "href": "/people/lee-harvey-oswald"}, {"name": "Ruth Paine", "href": "#"}]'::jsonb),

('lyndon-b-johnson',
 'Lyndon B. Johnson',
 '36th President of the United States, sworn in after Kennedy''s assassination.',
 '1908-08-27',
 '1973-01-22',
 'Stonewall, Texas',
 '36th President of the United States',
 'Lyndon Baines Johnson was Vice President under Kennedy and was sworn in as President aboard Air Force One at Love Field, approximately two hours after the assassination. He established the Warren Commission by Executive Order 11130 to investigate the assassination. He served as President until 1969, overseeing major civil rights legislation and the escalation of the Vietnam War.',
 '[{"title": "Warren Commission Executive Order", "href": "#"}]'::jsonb,
 '[{"title": "Swearing In Ceremony", "href": "#"}, {"title": "JFK Assassination", "href": "#"}]'::jsonb,
 '[{"name": "John F. Kennedy", "href": "/people/john-f-kennedy"}]'::jsonb),

('abraham-zapruder',
 'Abraham Zapruder',
 'Dallas clothing manufacturer who filmed the assassination with his 8mm home movie camera.',
 '1905-05-15',
 '1970-08-30',
 'Kovel, Russian Empire (now Ukraine)',
 'Clothing Manufacturer',
 'Abraham Zapruder was a Dallas dress manufacturer who captured the assassination on his Bell & Howell 8mm home movie camera. The 26.6-second film, known as the Zapruder film, is considered the most complete recording of the assassination and has been crucial evidence in all subsequent investigations. He sold the original film to Life magazine for $150,000.',
 '[{"title": "Zapruder Film Analysis", "href": "#"}, {"title": "Warren Commission Testimony", "href": "#"}]'::jsonb,
 '[{"title": "JFK Assassination", "href": "#"}]'::jsonb,
 '[]'::jsonb),

('clay-shaw',
 'Clay Shaw',
 'New Orleans businessman tried and acquitted of conspiracy to assassinate President Kennedy.',
 '1913-03-17',
 '1974-08-15',
 'Kentwood, Louisiana',
 'Businessman, Trade Mart Director',
 'Clay LaVerne Shaw was a decorated World War II veteran and director of the International Trade Mart in New Orleans. In 1967, New Orleans District Attorney Jim Garrison charged Shaw with conspiring to assassinate President Kennedy. Shaw was the only person ever brought to trial for the assassination. He was acquitted in 1969 after less than an hour of jury deliberation.',
 '[{"title": "Garrison Investigation Files", "href": "#"}, {"title": "Trial Transcripts", "href": "#"}]'::jsonb,
 '[{"title": "Shaw Trial", "href": "#"}]'::jsonb,
 '[{"name": "David Ferrie", "href": "/people/david-ferrie"}]'::jsonb),

('david-ferrie',
 'David Ferrie',
 'Pilot and alleged associate of Lee Harvey Oswald, investigated by Jim Garrison.',
 '1918-03-18',
 '1967-02-22',
 'Cleveland, Ohio',
 'Pilot, Private Investigator',
 'David William Ferrie was a pilot, amateur cancer researcher, and alleged associate of Lee Harvey Oswald through the Civil Air Patrol in New Orleans. He was investigated by Jim Garrison as part of a suspected conspiracy. Ferrie died of a brain hemorrhage in February 1967, shortly after Garrison''s investigation became public. His death was ruled natural causes, though controversy surrounds the circumstances.',
 '[{"title": "Garrison Investigation Files", "href": "#"}]'::jsonb,
 '[{"title": "Civil Air Patrol", "href": "#"}]'::jsonb,
 '[{"name": "Lee Harvey Oswald", "href": "/people/lee-harvey-oswald"}, {"name": "Clay Shaw", "href": "/people/clay-shaw"}]'::jsonb),

('earl-warren',
 'Earl Warren',
 'Chief Justice of the United States who chaired the Warren Commission.',
 '1891-03-19',
 '1974-07-09',
 'Los Angeles, California',
 'Chief Justice of the United States',
 'Earl Warren served as the 14th Chief Justice of the United States from 1953 to 1969. President Johnson appointed him to chair the commission investigating the Kennedy assassination, which became known as the Warren Commission. The commission''s report, released in September 1964, concluded that Lee Harvey Oswald acted alone. Warren''s legacy also includes landmark civil rights decisions such as Brown v. Board of Education.',
 '[{"title": "Warren Commission Report", "href": "#"}]'::jsonb,
 '[{"title": "Warren Commission Hearings", "href": "#"}]'::jsonb,
 '[]'::jsonb),

('george-de-mohrenschildt',
 'George de Mohrenschildt',
 'Russian-born petroleum geologist who befriended Lee Harvey Oswald in Dallas.',
 '1911-04-17',
 '1977-03-29',
 'Mozyr, Russian Empire (now Belarus)',
 'Petroleum Geologist',
 'George de Mohrenschildt was a Russian-born petroleum geologist who befriended Lee Harvey Oswald after his return from the Soviet Union. Despite their significant differences in social status, de Mohrenschildt and his wife Jeanne became close to the Oswalds in Dallas. He testified before the Warren Commission and later the HSCA. He died of a self-inflicted gunshot wound on the day an HSCA investigator arrived to interview him.',
 '[{"title": "Warren Commission Testimony", "href": "#"}, {"title": "HSCA Interview", "href": "#"}]'::jsonb,
 '[{"title": "Friendship with Oswald", "href": "#"}]'::jsonb,
 '[{"name": "Lee Harvey Oswald", "href": "/people/lee-harvey-oswald"}, {"name": "Marina Oswald Porter", "href": "/people/marina-oswald-porter"}]'::jsonb);
